[package]
name = "sidecar"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[dependencies]
serpentine_internal.workspace = true

log.workspace = true
simple_logger = { version = "5.2.0", default-features = false }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "net", "io-util", "fs"] }
nix = { workspace = true, features = ["fs", "mount"] }
uuid.workspace = true
rust-cni = { version = "0.1.2", default-features = false }
netns-rs = { version = "0.2.0", default-features = false }
rand = { version = "0.10.2", default-features = false, features = ["sys_rng", "std"] }
typed-path.workspace = true

[lints]
workspace = true
